[credentials.usernames.admin]
email = "nawatcore@outlook.com"
name = "Fredy"
password = "Empir3s00199+!"

[credentials.usernames.staff]
email = "nawatcore@outlook.com"
name = "Mercy"
password = "Basti&Chiricuto"