[credentials.usernames.admin]
email = "admin@nawatcore.com"
name = "Fredy"
password = "Empir3s00199+!"

[credentials.usernames.staff]
email = "staff@nawatcore.com"
name = "Mercy"
password = "Basti&Chiricuto"